import type { CourseSection } from "./types";

export const LEARNING_PATH: CourseSection[] = [
  {
    id: "intro",
    title: "Foundations",
    definition: "From elementary objects to structured abstractions — the opening chapters every classic text begins with.",
    color: "#6366F1",
    concepts: [
      "Elementary Data Objects concepts",
      "Necessity of Structured Data",
      "Types of Data Structures",
      "Linear vs Nonlinear Data Structures",
      "Data representation ideas",
    ],
  },
  {
    id: "arrays",
    title: "Arrays & Memory",
    definition: "Contiguous storage, indexing, and matrix algebra — Horowitz and CLRS treat arrays as the bridge to everything else.",
    color: "#3B82F6",
    concepts: [
      "Representation in Memory",
      "Traversing LA",
      "Insertion & Deletion in LA",
      "Multidimensional Arrays",
      "Algebra of Matrices",
      "Sparse Matrices representation",
    ],
  },
  {
    id: "stack",
    title: "Stacks & Expressions",
    definition: "LIFO discipline, Polish notation, and compiler parsing — Knuth devoted entire sections to expression evaluation.",
    color: "#F97316",
    concepts: [
      "Stack Representation",
      "PUSH and POP Operations",
      "Polish & Reverse Polish Notation",
      "Evaluation of Postfix Expressions",
      "Transforming Infix to Postfix",
      "Recursion Applications",
    ],
  },
  {
    id: "queue",
    title: "Queues & Recursion",
    definition: "FIFO scheduling, priority queues, and the recursive mindset that powers divide-and-conquer.",
    color: "#22C55E",
    concepts: [
      "Insertion & Deletion logic",
      "Priority Queues",
      "Factorial Function recursion",
      "Fibonacci Sequence",
      "Ackermann Function",
      "Towers of Hanoi",
    ],
  },
  {
    id: "linked",
    title: "Linked Lists",
    definition: "Pointer-based dynamic structures — Weiss and Goodrich emphasize ADTs before implementation details.",
    color: "#06B6D4",
    concepts: [
      "Memory Representation",
      "Traversing & Searching",
      "Insertion & Deletion",
      "Circular Linked Lists",
      "Header Linked Lists",
      "Two-Way (Doubly) Lists",
    ],
  },
  {
    id: "complexity",
    title: "Complexity Analysis",
    definition: "Asymptotic notation and case analysis — CLRS Chapter 3 is the definitive treatment.",
    color: "#EF4444",
    concepts: [
      "Algorithm & Flowcharting",
      "Asymptotic Notations",
      "Best Case Analysis",
      "Worst Case Analysis",
      "Average Case Analysis",
      "Complexity of Specific Algorithms",
    ],
  },
  {
    id: "sort-search",
    title: "Sorting & Searching",
    definition: "The algorithmic core — from linear scan to hash tables, spanning Sedgewick and CLRS.",
    color: "#EC4899",
    concepts: [
      "Linear & Binary Search",
      "Insertion / Selection Sort",
      "Bubble / Quick / Merge Sort",
      "Hash Function architecture",
      "Collision Resolution strategies",
    ],
  },
  {
    id: "trees",
    title: "Trees & Heaps",
    definition: "Hierarchical data — BST, balanced trees, heaps, and B-trees from the masters.",
    color: "#A855F7",
    concepts: [
      "Tree Terminology",
      "Binary Tree Memory representation",
      "Binary Tree Traversals",
      "Balanced BST (AVL & Red-Black)",
      "Heaps & Heap Sort",
      "B Trees & General Tree logic",
    ],
  },
];
